[package]
name = "thinp"
version = "0.1.0"
authors = ["Joe Thornber <ejt@redhat.com>"]
edition = "2018"
license = "GPL3"

[dependencies]
anyhow = "1.0"
byteorder = "1.3"
clap = "2.33"
crc32c = "0.6"
flate2 = "1.0"
fixedbitset = "0.3"
libc = "0.2.71"
quick-xml = "0.18"
nix = "0.17"
nom = "5.1"
num_cpus = "1.13"
rand = "0.7"
tempfile = "3.1"
num-traits = "0.2"
num-derive = "0.3"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
